arch: arm64

services: 
- docker

script:
- export DB_USER=root
- export DB_PASSWORD=test123456
- export DB_HOST=127.0.0.1
- export DB_PORT=13306
- export REDIS_HOST=127.0.0.1
- export REDIS_PORT=16379
- export API_PORT=18080
- export API_HOST=127.0.0.1

- docker rm -f falcon-mysql falcon-redis falcon-plus &> /dev/null
- docker run --name falcon-mysql -e MYSQL_ROOT_PASSWORD=$DB_PASSWORD -p $DB_PORT:3306 -d mysql/mysql-server

- docker run --name falcon-redis -p $REDIS_PORT:6379 -d redis:4-alpine3.8
- for x in `ls ./scripts/mysql/db_schema/*.sql`; do
    echo "- - -" $x ...
    mysql -h $DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASSWORD < $x
  done
- docker run --name mysql1 -d mysql/mysql-server
- docker logs mysql1
- docker stop mysql1 && docker rm mysql1
- docker run --name mysql1 -e MYSQL_ROOT_HOST=% -p 3306:3306 -d mysql/mysql-server
- docker logs mysql1 2>&1 | grep GENERATED 
- docker exec -it mysql1 mysql -u root -p
