arch: arm64

services: 
- docker

script:
- docker run --name mysql1 -d mysql/mysql-server
- docker logs mysql1
- docker stop mysql1 && docker rm mysql1
- docker run --name mysql1 -e MYSQL_ROOT_HOST=% -P 3306:3306 -d mysql/mysql-server
- docker logs mysql1 2>&1 | grep GENERATED 
- docker exec -it mysql1 mysql -u root -p
